-- =============================================
-- Tablo: auth.email_verification_tokens
-- Açıklama: Email doğrulama token tablosu
-- Backend UUID token üretir, DB saklar ve doğrular
-- =============================================

DROP TABLE IF EXISTS auth.email_verification_tokens CASCADE;

CREATE TABLE auth.email_verification_tokens (
    id BIGSERIAL PRIMARY KEY,
    player_id BIGINT NOT NULL,                       -- Oyuncu ID (FK: auth.players)
    token UUID NOT NULL,                             -- Backend tarafından üretilen UUID token
    expires_at TIMESTAMPTZ NOT NULL,                 -- Token son kullanma tarihi
    used_at TIMESTAMPTZ,                             -- Kullanım zamanı (NULL = henüz kullanılmadı)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()    -- Oluşturulma zamanı
);

COMMENT ON TABLE auth.email_verification_tokens IS 'Email verification tokens generated by backend. Token is UUID, validated by DB on verify.';
