-- =============================================
-- Tablo: auth.password_reset_tokens
-- Açıklama: Şifre sıfırlama token tablosu
-- Backend UUID token üretir, DB saklar ve doğrular
-- =============================================

DROP TABLE IF EXISTS auth.password_reset_tokens CASCADE;

CREATE TABLE auth.password_reset_tokens (
    id BIGSERIAL PRIMARY KEY,
    player_id BIGINT NOT NULL,                       -- Oyuncu ID (FK: auth.players)
    token UUID NOT NULL,                             -- Backend tarafından üretilen UUID token
    expires_at TIMESTAMPTZ NOT NULL,                 -- Token son kullanma tarihi
    used_at TIMESTAMPTZ,                             -- Kullanım zamanı (NULL = henüz kullanılmadı)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()    -- Oluşturulma zamanı
);

COMMENT ON TABLE auth.password_reset_tokens IS 'Password reset tokens generated by backend. Token is UUID, validated by DB on reset confirm.';
